/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppMenu {
    }
    interface AppRoot {
    }
    interface AppSvg {
        "margin": number;
        "pageHeight": number;
        "pageWidth": number;
        "renderAsText": boolean;
    }
}
declare global {
    interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {
    }
    var HTMLAppMenuElement: {
        prototype: HTMLAppMenuElement;
        new (): HTMLAppMenuElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSvgElement extends Components.AppSvg, HTMLStencilElement {
    }
    var HTMLAppSvgElement: {
        prototype: HTMLAppSvgElement;
        new (): HTMLAppSvgElement;
    };
    interface HTMLElementTagNameMap {
        "app-menu": HTMLAppMenuElement;
        "app-root": HTMLAppRootElement;
        "app-svg": HTMLAppSvgElement;
    }
}
declare namespace LocalJSX {
    interface AppMenu {
    }
    interface AppRoot {
    }
    interface AppSvg {
        "margin"?: number;
        "pageHeight"?: number;
        "pageWidth"?: number;
        "renderAsText"?: boolean;
    }
    interface IntrinsicElements {
        "app-menu": AppMenu;
        "app-root": AppRoot;
        "app-svg": AppSvg;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-menu": LocalJSX.AppMenu & JSXBase.HTMLAttributes<HTMLAppMenuElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-svg": LocalJSX.AppSvg & JSXBase.HTMLAttributes<HTMLAppSvgElement>;
        }
    }
}
